hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_signal_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_signal_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_egamma_signal_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_signal_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_rareBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_rareBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_egamma_rareBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_rareBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_qcd_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_qcd_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_egamma_qcd_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_qcd_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_eleBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_eleBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_egamma_eleBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_eleBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_VGBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_VGBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_egamma_VGBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_VGBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_egamma_jetbkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_egamma_jetbkg_2016p*.root /uscms_data/d3/tmishra/Output/signalTree_egamma_jetbkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_egamma_jetbkg_2018.root

hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_signal_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_signal_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_mg_signal_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_signal_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_rareBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_rareBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_mg_rareBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_rareBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_qcd_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_qcd_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_mg_qcd_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_qcd_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_eleBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_eleBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_mg_eleBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_eleBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_VGBkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_VGBkg_2016p*VFP.root /uscms_data/d3/tmishra/Output/signalTree_mg_VGBkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_VGBkg_2018.root
hadd -f /uscms_data/d3/tmishra/Output/signalTree_mg_jetbkg_2020.root /uscms_data/d3/tmishra/Output/signalTree_mg_jetbkg_2016p*.root /uscms_data/d3/tmishra/Output/signalTree_mg_jetbkg_2017.root /uscms_data/d3/tmishra/Output/signalTree_mg_jetbkg_2018.root
