// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/uscms/homes/t/tmishra/work/CMSSW_10_2_22/src/SUSYAnalysis/test/VGamma/fit/./plotGauss.C";

#endif
