mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_DYJetsToLL_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_DYJetsToLL_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_TTGJets_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_TTGJets_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_TTJets_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_TTJets_2018.root 
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGJet130_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGJet130_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGJet40_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGJet40_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGToLNuG_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WGToLNuG_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WWG_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WWG_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WW_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WW_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WZG_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WZG_2018.root
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WZ_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_WZ_2018.root 
mv /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_ZGToLLG_2018_modified.root /eos/uscms/store/user/tmishra/VGamma/resTree_VGamma_ZGToLLG_2018.root
